### ISSUE TITLE
MyFont 웹페이지 USE 부분에서 아무것도 입력하지 않고 제출 누를시 오류

### ISSUE THREAD

**Issue by GeunTeakOh** [kookmin-sw/2018-cap1-12#20]
MyFont 웹페이지 USE 부분에서 아무것도 입력하지 않고 제출 누를시 오류가 발생합니다.

이를 try ~ catch 문을 이용하여 alert 경고창을 출력하여 사용자에게 파일을 선택해야한다고

알려주면 좋을 것 같습니다

**Comment by kimsk9410** [comment]
확인부탁드립니다.

**Comment by GeunTeakOh** [comment]
확인하였습니다.
