### ISSUE TITLE
폰트 생성 목표 범위

### ISSUE THREAD

**Issue by Hwangyonghwan** [kookmin-sw/2018-cap1-12#3]
현 프로젝트는 사용자의 한글 글씨체만을 폰트로 생성하는 것을 프로젝트 목표로 하는데 한글 이외의 특수문자나 영어 알파벳은 사용자의 필기체가 아닌 다른 글씨체로 나오게 된다. 그렇다면 완벽한 폰트라고 할 수 없는데 특수문자 나 알파벳은 프로젝트 범위로 포함을 시킬 것인가 포함 시키지 않을 것인가 정해야 한다. 만약 포함시키지 않는다면 특수문자나 알파벳은 디폴트 폰트로 어떤 폰트를 적용시킬지에 대한 이슈가 있다.

**Comment by GeunTeakOh** [comment]
현재 졸업작품 마감일 까지 25일 남았는데, 하나의 모델을 학습하는데에는 약 1일이 소요되므로 11,172개의 모든 글자에 대한 이미지를 생성하기에는 무리가 있다고 판단하여 몇개의 문자로 하나의 문장을 생성하는 것이 좋다고 생각합니다.
