### ISSUE TITLE
use 에서 이미지파일을 넣고 crop 하는 부분에서 소제목 추가

### ISSUE THREAD

**Issue by GeunTeakOh** [kookmin-sw/2018-cap1-12#32]
use 에서 이미지 파일을 넣고 crop 을 하는 화면에서

위에 소제목이 없어 사용자는 어떤 작업을 진행중인지 알기 어렵습니다.

따라서 소제목을 추가해주시면 감사합니다.

**Comment by kimsk9410** [comment]
완료
