### ISSUE TITLE
폰트 생성 모델의 데이터

### ISSUE THREAD

**Issue by leekitten123** [kookmin-sw/2018-cap1-12#4]
폰트 모델을 생성하는 과정에서 사용하는 데이터에 대한 문제입니다.

학습 데이터에 특이한 모양의 글자를 데이터로 포함할 것인지 혹은 포함하지 않을 것인지 결정해야 합니다.

특이한 모양의 글자를 사용할 경우 Overfitting의 문제가 있을 수 있습니다.

그러므로 특이한 모양의 글자를 정의하는 기준과 그 글자의 데이터 포함 여부를 결정해야 하는 이슈가 있습니다.

**Comment by GeunTeakOh** [comment]
폰트를 살펴보면 몇몇 글자는 깨져있는 글자가 있는데 이를 제외한다면 overfitting 방지를 위해 추가하는 것이 좋다고 생각합니다.

**Comment by kimsk9410** [comment]
특이함에도 기준이 있어야된다고 생각합니다.
실제 문자의 모양을 많이 벗어나거나 깨져있는 데이터를 사용한다면 이는 학습에 도움이 되지 않으 뿐더러 해가 될 것이라 생각하며 Overfitting문제의 경우 데이터 회전이나 문자의 위치 조정, 크기 조정 등으로 해결하는 방법도 좋을 것 같습니다.
