### ISSUE TITLE
fonts 중복 이름 버그

### ISSUE THREAD

**Issue by GeunTeakOh** [kookmin-sw/2018-cap1-12#41]
생성한 fonts 가 기존에 생성하였다가 삭제한 이름과 일치한 새로운 폰트를 생성하였을 시

웹에서 이미 삭제한 예전 폰트를 가져와서 사용하게 된다.

이는 크롬에서의 캐시 버그로 추측된다.

**Comment by kimsk9410** [comment]
완료
