### ISSUE TITLE
이미지 후처리

### ISSUE THREAD

**Issue by Hwangyonghwan** [kookmin-sw/2018-cap1-12#42]
생성된 이미지 delation하고
기존의 것과 비교하여 더 결과가 나은 것으로 업데이트 해주세요

**Comment by GeunTeakOh** [comment]
<img width="602" alt="2018-05-27 5 12 09" src="https://user-images.githubusercontent.com/21329735/40584141-2ea534b6-61d7-11e8-9a56-d81fda4e325a.png">
<img width="641" alt="2018-05-27 5 42 25" src="https://user-images.githubusercontent.com/21329735/40584142-30faf8c2-61d7-11e8-805e-a9b1592dd04e.png">

위 2사지진을 비교해보면 dilation을 1번한 결과가 기존 결과보다 좋지 않아서 구현은 하였지만 적용하지 않는 것이 더 좋을것 같다고 판단하였습니다.

다른 방식으로 이미지를 후처리 하는 것을 생각해봐야 할 것 같습니다
