### ISSUE TITLE
use 부분에서 파일 이름을 숫자로 받아지는 버그 발생

### ISSUE THREAD

**Issue by GeunTeakOh** [kookmin-sw/2018-cap1-12#48]
use 부분에서 파일의 이름이 숫자로 시작하는 경우 경고창을 띄우며 입력을 받지 않는 처리를 하였다.

하지만 키보드로 빠르게 숫자를 입력하면 경고창이 뜨지 않고 숫자로 시작하는 파일명이 받아지게 된다.

따라서 이 버그를 수정해야 한다.

**Comment by kimsk9410** [comment]
완료
