### ISSUE TITLE
폰트 생성 목표 범위-2

### ISSUE THREAD

**Issue by kimsk9410** [kookmin-sw/2018-cap1-12#5]
모든 한글 조합과 특수문자, 알파벳 대소문자를 모두 합하면 11,172개이다. 이 중에는 잘 사용되지 않는 한글 조합들이 다수 포함되어 있다.
잘 사용되지 않는 한글 조합들을 제외한다면 2,444개로 현저히 줄어든다.
따라서 실제 사용되는 폰트들에도 잘 사용되는 2,444개의 문자만 포함하는 폰트들이 존재하는데, 이 프로젝트에서의 폰트 생성 목표 범위를 어떤 것으로 잡는 것이 좋은지 고민해봐야 한다.

**Comment by GeunTeakOh** [comment]
현재 하나의 음절을 하나의 음절로 변환하도록 학습하는 모델을 만드는데에 1일이 걸린다. 하지만 기간이 얼마 남지 않았으므로 입력이 될 문장과 그 입력으로 결과를 내뿜을 하나의 문장을 선정하는것이 좋을것 같다. 하나의 문장은 10개정도의 음절이 되는 것이 적절하다. 현재 서버를 2개 운영하여서 1일에 2개의 음절을 생성할수 있으나 이미지 후처리나 학습모델 통합 등 다른 개발 내용도 남았기에 하나의 문장만을 생성하는 폰트를 생성하는 것이 적절할 것 같다.
