### ISSUE TITLE
현재 사용중인 merge모듈 속도 개선 방안제시

### ISSUE THREAD

**Issue by kimsk9410** [kookmin-sw/2018-cap1-12#6]
오근택학생이 작성한 merge의 속도가 매우 느린 이슈 확인.

**Comment by kimsk9410** [comment]
현재 오근택군이 작성한 merge모듈은 모든 파일을 확인하여 같은 이름을 가진 파일의 존재를 확인하는데 이 때문에 속도가 현저히 느립니다. 이를 모든 파일을 확인하는 것이 아닌 해당 이름을 가진 파일을 바로 입력하여 없는 경우 Exception처리를 하는 방안으로 개선하고자 합니다.

**Comment by GeunTeakOh** [comment]
현재 코드는 O(n^2) 의 시간복잡도를 가진 상태이지만 김선규군이 말씀하신 방식인 경우 O(n)의 시간 복잡도가 될 것 같습니다. 좋은 방안 같습니다
