### ISSUE TITLE
학습된 모델에 실제 손글씨 데이터 적용 시 문제 발생

### ISSUE THREAD

**Issue by kimsk9410** [kookmin-sw/2018-cap1-12#7]
7371개의 폰트데이터, 48000번의 학습된 DiscoGAN모델을 이용하여 실제 손글씨 데이터를 적용했을 때 기대와는 다르게 제대로 생성하지 못하고 지저분한 데이터가 결과로 나옴.
이에 대한 문제의 원인과 해결 방안들을 찾아야 한다.

**Comment by GeunTeakOh** [comment]
현재 우리는 사용자의 입력을 이미지 파일로 변환하는 것은 몰스킨 스마트 라이팅 펜(시제품)을 이용하고 있다.
우리 제품이 아닌 시제품을 사용함으로써 생기는 문제점일 수도 있다고 생각한다.
현재 우리의 서브 모듈인 ttf2jpg 를 이용한 것과 몰스킨 스마트 라이팅 펜을 이용하여 유저의 글씨체를 직접 이미지로 만든 이미지 파일의 픽셀 분포가 상이하다. 즉, 학습한 픽셀 데이터와 사용자의 입력을 받아서 이미지로 만든 픽셀 데이터와의 오차로 인해 손글씨 데이터가 정확하게 생성되지 않는 것 같다.

**Comment by GeunTeakOh** [comment]
![sub_module](https://user-images.githubusercontent.com/21329735/39670181-02a0f5d8-513a-11e8-92d0-13f5f547808a.png)
 [ttf2jpg 를 이용한 이미지의 픽셀 분포 : 확대하여 보면 0 주위와 255 주위에 픽셀이 분포되어 있다.]

![pen](https://user-images.githubusercontent.com/21329735/39670182-049ebb22-513a-11e8-8883-92f927438149.png)
[시제품을 이용한 이미지의 픽셀 분포 : 0부분에는 데이터가 없고 20주위와 255주위에 픽셀이 분포되어 있다.]
